In [1]:
import polars as pl

In [2]:
image_path = "/mnt/czolab-storage-01/acruzcar/MAINCE_output/Cohort2_v2/V01/QC/Images/Measurements/Image.txt"

df = pl.read_csv(image_path, separator='\t')
df

shape: (7_776, 83)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Count_Cel ┆ Count_Ill ┆ Count_Ill ┆ Count_Nuc ┆ … ┆ Intensity ┆ Metadata_ ┆ Metadata_ ┆ Metadata │
│ ls        ┆ um_artifa ┆ um_artifa ┆ lei       ┆   ┆ _UpperQua ┆ Field     ┆ Plate     ┆ _Well    │
│ ---       ┆ cts       ┆ cts_filte ┆ ---       ┆   ┆ rtileInte ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ ---       ┆ red       ┆ f64       ┆   ┆ nsi…      ┆ i64       ┆ i64       ┆ str      │
│           ┆ f64       ┆ ---       ┆           ┆   ┆ ---       ┆           ┆           ┆          │
│           ┆           ┆ f64       ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 70.0      ┆ 4.0       ┆ 4.0       ┆ 73.0      ┆ … ┆ 0.131762  ┆ 9         ┆ 14        ┆ G04      │
│ 42.0      ┆ 5.0       ┆ 5.0       ┆ 43.0      ┆ … ┆ 0.063005  ┆ 8         ┆ 14        ┆ C05      │
│ 69.0      ┆ 0.0       ┆ 0.0       ┆ 69.0      ┆ … ┆ 0.132631  ┆ 1         ┆ 14        ┆ G04      │
│ 91.0      ┆ 1.0       ┆ 1.0       ┆ 92.0      ┆ … ┆ 0.131319  ┆ 7         ┆ 14        ┆ B12      │
│ 101.0     ┆ 1.0       ┆ 1.0       ┆ 106.0     ┆ … ┆ 0.165438  ┆ 3         ┆ 14        ┆ F01      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 99.0      ┆ 2.0       ┆ 2.0       ┆ 102.0     ┆ … ┆ 0.150149  ┆ 6         ┆ 18        ┆ A01      │
│ 78.0      ┆ 2.0       ┆ 2.0       ┆ 79.0      ┆ … ┆ 0.122087  ┆ 5         ┆ 18        ┆ C06      │
│ 83.0      ┆ 2.0       ┆ 2.0       ┆ 84.0      ┆ … ┆ 0.127153  ┆ 7         ┆ 18        ┆ B03      │
│ 74.0      ┆ 1.0       ┆ 1.0       ┆ 77.0      ┆ … ┆ 0.103166  ┆ 3         ┆ 18        ┆ F10      │
│ 76.0      ┆ 2.0       ┆ 2.0       ┆ 78.0      ┆ … ┆ 0.102708  ┆ 1         ┆ 18        ┆ H11      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
sorted(df['Metadata_Plate'].unique())

[10, 11, 12, 13, 14, 15, 16, 17, 18]

In [19]:
df1 = df.group_by(['Metadata_Plate', 'Metadata_Well']).agg()
df1

shape: (864, 2)
┌────────────────┬───────────────┐
│ Metadata_Plate ┆ Metadata_Well │
│ ---            ┆ ---           │
│ i64            ┆ str           │
╞════════════════╪═══════════════╡
│ 11             ┆ D07           │
│ 11             ┆ D09           │
│ 10             ┆ C06           │
│ 14             ┆ D11           │
│ 14             ┆ H10           │
│ …              ┆ …             │
│ 11             ┆ E04           │
│ 10             ┆ G01           │
│ 16             ┆ C09           │
│ 11             ┆ C06           │
│ 11             ┆ G12           │
└────────────────┴───────────────┘

In [1]:
df.group_by(['Metadata_Plate','Metadata_Well','Metadata_Field']).agg()

NameError: name 'df' is not defined

In [3]:
import numpy as np

# ── columnas que agrega load_qc_tsv, detectadas del df real ──────────────
mean_cols = [c for c in df.columns if c.startswith("ImageQuality_")
             and any(k in c for k in ("PowerLogLogSlope", "MedianIntensity",
                                       "FocusScore"))]
pct_cols  = [c for c in df.columns
             if c.startswith("ImageQuality_PercentMaximal_")
             or c.startswith("ImageQuality_PercentMinimal_")]
sum_cols  = [c for c in df.columns if c.startswith("Count_")]

gkeys = ["Metadata_Plate", "Metadata_Well"]
gkeys = [c for c in gkeys if c in df.columns]

# ── well-level (como load_qc_tsv) ────────────────────────────────────────
well = df.group_by(gkeys).agg(
    [pl.col(c).mean() for c in mean_cols] +
    [pl.col(c).mean() for c in pct_cols] +
    [pl.col(c).sum()  for c in sum_cols]
)

# ── site-level (como load_qc_sites) ──────────────────────────────────────
gkeys_s = gkeys + ["Metadata_Field"]
site = df.group_by(gkeys_s).agg(
    [pl.col(c).mean() for c in mean_cols] +
    [pl.col(c).mean() for c in pct_cols] +
    [pl.col(c).sum()  for c in sum_cols]
)

# ── sanity: ¿cuántos sites por well? ─────────────────────────────────────
per_well = site.group_by(gkeys).len()
print("sites por well — min/max:",
      per_well["len"].min(), "/", per_well["len"].max())

# ── tomar un well de muestra y comparar ──────────────────────────────────
w0 = well.row(0, named=True)
key = {k: w0[k] for k in gkeys}
sub = site.filter(
    pl.all_horizontal([pl.col(k) == v for k, v in key.items()])
)

mcol = mean_cols[0]
ccol = sum_cols[0]

mean_of_sites = sub[mcol].mean()
sum_of_sites  = sub[ccol].sum()

print(f"\nwell de muestra: {key}\n")
print(f"[MEAN] {mcol}")
print(f"   mean(sites) = {mean_of_sites}")
print(f"   well-level  = {w0[mcol]}")
print(f"   MATCH: {abs(mean_of_sites - w0[mcol]) < 1e-6}\n")

print(f"[SUM]  {ccol}")
print(f"   sum(sites) = {sum_of_sites}")
print(f"   well-level = {w0[ccol]}")
print(f"   MATCH: {abs(sum_of_sites - w0[ccol]) < 1e-6}")

sites por well — min/max: 9 / 9

well de muestra: {'Metadata_Plate': 16, 'Metadata_Well': 'H07'}

[MEAN] ImageQuality_FocusScore_Brightfield
   mean(sites) = 0.0031197446307122604
   well-level  = 0.003119744630712261
   MATCH: True

[SUM]  Count_Cells
   sum(sites) = 672.0
   well-level = 672.0
   MATCH: True

In [2]:
import polars as pl
from pathlib import Path

In [23]:
path_C2 = Path("/mnt/czolab-storage-01/acruzcar/MAINCE_output/Cohort2/V01/QC/Measurements/Image.parquet")
path_C4 = Path("/mnt/czolab-storage-01/acruzcar/MAINCE_output/Cohort4/V01/QC/Measurements/Image.parquet")
df = pl.read_parquet(path_C4)
df.head()

shape: (5, 83)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Count_Cel ┆ Count_Ill ┆ Count_Ill ┆ Count_Nuc ┆ … ┆ Intensity ┆ Metadata_ ┆ Metadata_ ┆ Metadata │
│ ls        ┆ um_artifa ┆ um_artifa ┆ lei       ┆   ┆ _UpperQua ┆ Field     ┆ Plate     ┆ _Well    │
│ ---       ┆ cts       ┆ cts_filte ┆ ---       ┆   ┆ rtileInte ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ ---       ┆ red       ┆ f64       ┆   ┆ nsi…      ┆ i64       ┆ i64       ┆ str      │
│           ┆ f64       ┆ ---       ┆           ┆   ┆ ---       ┆           ┆           ┆          │
│           ┆           ┆ f64       ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 112.0     ┆ 1.0       ┆ 1.0       ┆ 112.0     ┆ … ┆ 0.11191   ┆ 8         ┆ 39        ┆ G05      │
│ 72.0      ┆ 3.0       ┆ 3.0       ┆ 72.0      ┆ … ┆ 0.065782  ┆ 7         ┆ 39        ┆ F12      │
│ 88.0      ┆ 2.0       ┆ 2.0       ┆ 88.0      ┆ … ┆ 0.08072   ┆ 4         ┆ 39        ┆ G05      │
│ 85.0      ┆ 1.0       ┆ 1.0       ┆ 85.0      ┆ … ┆ 0.089647  ┆ 5         ┆ 39        ┆ C04      │
│ 84.0      ┆ 1.0       ┆ 1.0       ┆ 84.0      ┆ … ┆ 0.089815  ┆ 3         ┆ 39        ┆ B01      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [91]:
img = pl.read_parquet(path_C4)
cols = ["Metadata_Plate", "Metadata_Well", "Metadata_Field", "Count_Nuclei",
        "Intensity_Percentile_10_Syto", "Intensity_UpperQuartileIntensity_Syto",
        "Intensity_MeanIntensity_Syto", "Intensity_MedianIntensity_Syto", "ImageQuality_TotalIntensity_Syto", "ImageQuality_TotalArea_Syto",
        "Intensity_Percentile_90_Syto"]

In [92]:
img2 = img[cols]
img2

shape: (9_503, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Metadata_ ┆ Metadata_ ┆ Metadata_ ┆ Count_Nuc ┆ … ┆ Intensity ┆ ImageQual ┆ ImageQual ┆ Intensit │
│ Plate     ┆ Well      ┆ Field     ┆ lei       ┆   ┆ _MedianIn ┆ ity_Total ┆ ity_Total ┆ y_Percen │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ tensity_S ┆ Intensity ┆ Area_Syto ┆ tile_90_ │
│ i64       ┆ str       ┆ i64       ┆ f64       ┆   ┆ yto       ┆ _Sy…      ┆ ---       ┆ Syto     │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 39        ┆ G05       ┆ 8         ┆ 112.0     ┆ … ┆ 0.066835  ┆ 97196.516 ┆ 1166400   ┆ 0.167605 │
│ 39        ┆ F12       ┆ 7         ┆ 72.0      ┆ … ┆ 0.027619  ┆ 61863.26  ┆ 1166400   ┆ 0.121141 │
│ 39        ┆ G05       ┆ 4         ┆ 88.0      ┆ … ┆ 0.03003   ┆ 70112.805 ┆ 1166400   ┆ 0.143786 │
│ 39        ┆ C04       ┆ 5         ┆ 85.0      ┆ … ┆ 0.040635  ┆ 77932.484 ┆ 1166400   ┆ 0.156056 │
│ 39        ┆ B01       ┆ 3         ┆ 84.0      ┆ … ┆ 0.040146  ┆ 79524.39  ┆ 1166400   ┆ 0.16466  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 33        ┆ F05       ┆ 2         ┆ 78.0      ┆ … ┆ 0.036973  ┆ 86214.09  ┆ 1166400   ┆ 0.180316 │
│ 33        ┆ H09       ┆ 7         ┆ 126.0     ┆ … ┆ 0.06981   ┆ 101230.95 ┆ 1166400   ┆ 0.177752 │
│ 33        ┆ F08       ┆ 5         ┆ 95.0      ┆ … ┆ 0.048157  ┆ 83314.99  ┆ 1166400   ┆ 0.161151 │
│ 33        ┆ E07       ┆ 3         ┆ 90.0      ┆ … ┆ 0.053605  ┆ 88853.67  ┆ 1166400   ┆ 0.171771 │
│ 33        ┆ D02       ┆ 1         ┆ 0.0       ┆ … ┆ 0.019745  ┆ 23570.703 ┆ 1166400   ┆ 0.024216 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [93]:
img2 = img2.with_columns((pl.col("Intensity_Percentile_10_Syto") / pl.col("Intensity_Percentile_90_Syto")).alias("Ratio P10/P90"))
img2 = img2.with_columns((pl.col("ImageQuality_TotalIntensity_Syto") / pl.col("ImageQuality_TotalArea_Syto")).alias("Ratio Intensity"))
img2

shape: (9_503, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Metadata_ ┆ Metadata_ ┆ Metadata_ ┆ Count_Nuc ┆ … ┆ ImageQual ┆ Intensity ┆ Ratio     ┆ Ratio    │
│ Plate     ┆ Well      ┆ Field     ┆ lei       ┆   ┆ ity_Total ┆ _Percenti ┆ P10/P90   ┆ Intensit │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ Area_Syto ┆ le_90_Syt ┆ ---       ┆ y        │
│ i64       ┆ str       ┆ i64       ┆ f64       ┆   ┆ ---       ┆ o         ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ ---       ┆           ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 39        ┆ G05       ┆ 8         ┆ 112.0     ┆ … ┆ 1166400   ┆ 0.167605  ┆ 0.14594   ┆ 0.08333  │
│ 39        ┆ F12       ┆ 7         ┆ 72.0      ┆ … ┆ 1166400   ┆ 0.121141  ┆ 0.149389  ┆ 0.053038 │
│ 39        ┆ G05       ┆ 4         ┆ 88.0      ┆ … ┆ 1166400   ┆ 0.143786  ┆ 0.124801  ┆ 0.06011  │
│ 39        ┆ C04       ┆ 5         ┆ 85.0      ┆ … ┆ 1166400   ┆ 0.156056  ┆ 0.125647  ┆ 0.066815 │
│ 39        ┆ B01       ┆ 3         ┆ 84.0      ┆ … ┆ 1166400   ┆ 0.16466   ┆ 0.110833  ┆ 0.068179 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 33        ┆ F05       ┆ 2         ┆ 78.0      ┆ … ┆ 1166400   ┆ 0.180316  ┆ 0.113396  ┆ 0.073915 │
│ 33        ┆ H09       ┆ 7         ┆ 126.0     ┆ … ┆ 1166400   ┆ 0.177752  ┆ 0.124217  ┆ 0.086789 │
│ 33        ┆ F08       ┆ 5         ┆ 95.0      ┆ … ┆ 1166400   ┆ 0.161151  ┆ 0.130575  ┆ 0.071429 │
│ 33        ┆ E07       ┆ 3         ┆ 90.0      ┆ … ┆ 1166400   ┆ 0.171771  ┆ 0.12108   ┆ 0.076178 │
│ 33        ┆ D02       ┆ 1         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.024216  ┆ 0.63012   ┆ 0.020208 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [101]:
img3 = img2.filter((pl.col("Ratio P10/P90") > 0.5) )
img3.head(10)

shape: (10, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Metadata_ ┆ Metadata_ ┆ Metadata_ ┆ Count_Nuc ┆ … ┆ ImageQual ┆ Intensity ┆ Ratio     ┆ Ratio    │
│ Plate     ┆ Well      ┆ Field     ┆ lei       ┆   ┆ ity_Total ┆ _Percenti ┆ P10/P90   ┆ Intensit │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ Area_Syto ┆ le_90_Syt ┆ ---       ┆ y        │
│ i64       ┆ str       ┆ i64       ┆ f64       ┆   ┆ ---       ┆ o         ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ ---       ┆           ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 32        ┆ A07       ┆ 7         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.023346  ┆ 0.636601  ┆ 0.019288 │
│ 32        ┆ F07       ┆ 1         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.023651  ┆ 0.629677  ┆ 0.019881 │
│ 32        ┆ C11       ┆ 3         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.023011  ┆ 0.626658  ┆ 0.0191   │
│ 32        ┆ F07       ┆ 5         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.023789  ┆ 0.622835  ┆ 0.019339 │
│ 32        ┆ C11       ┆ 7         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.023713  ┆ 0.64157   ┆ 0.022661 │
│ 32        ┆ A04       ┆ 5         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.023743  ┆ 0.624036  ┆ 0.019841 │
│ 32        ┆ A04       ┆ 9         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.02359   ┆ 0.628719  ┆ 0.019522 │
│ 32        ┆ C11       ┆ 6         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.022721  ┆ 0.63734   ┆ 0.01985  │
│ 32        ┆ F07       ┆ 4         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.023941  ┆ 0.62014   ┆ 0.019937 │
│ 32        ┆ C11       ┆ 2         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.023285  ┆ 0.633028  ┆ 0.020087 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [94]:
img2.filter((pl.col("Metadata_Well") == "H02") & (pl.col("Metadata_Plate") == 39))

shape: (9, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Metadata_ ┆ Metadata_ ┆ Metadata_ ┆ Count_Nuc ┆ … ┆ ImageQual ┆ Intensity ┆ Ratio     ┆ Ratio    │
│ Plate     ┆ Well      ┆ Field     ┆ lei       ┆   ┆ ity_Total ┆ _Percenti ┆ P10/P90   ┆ Intensit │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ Area_Syto ┆ le_90_Syt ┆ ---       ┆ y        │
│ i64       ┆ str       ┆ i64       ┆ f64       ┆   ┆ ---       ┆ o         ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ ---       ┆           ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 39        ┆ H02       ┆ 6         ┆ 63.0      ┆ … ┆ 1166400   ┆ 0.103288  ┆ 0.15763   ┆ 0.040261 │
│ 39        ┆ H02       ┆ 3         ┆ 50.0      ┆ … ┆ 1166400   ┆ 0.091707  ┆ 0.176373  ┆ 0.037909 │
│ 39        ┆ H02       ┆ 4         ┆ 45.0      ┆ … ┆ 1166400   ┆ 0.077104  ┆ 0.197902  ┆ 0.034853 │
│ 39        ┆ H02       ┆ 9         ┆ 68.0      ┆ … ┆ 1166400   ┆ 0.110536  ┆ 0.150055  ┆ 0.044542 │
│ 39        ┆ H02       ┆ 5         ┆ 49.0      ┆ … ┆ 1166400   ┆ 0.077562  ┆ 0.20244   ┆ 0.034575 │
│ 39        ┆ H02       ┆ 1         ┆ 53.0      ┆ … ┆ 1166400   ┆ 0.096468  ┆ 0.169883  ┆ 0.039768 │
│ 39        ┆ H02       ┆ 7         ┆ 68.0      ┆ … ┆ 1166400   ┆ 0.112154  ┆ 0.151701  ┆ 0.045056 │
│ 39        ┆ H02       ┆ 2         ┆ 34.0      ┆ … ┆ 1166400   ┆ 0.061723  ┆ 0.258591  ┆ 0.033078 │
│ 39        ┆ H02       ┆ 8         ┆ 54.0      ┆ … ┆ 1166400   ┆ 0.104891  ┆ 0.157405  ┆ 0.042966 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [99]:
# Pozo casi vacio
img2.filter((pl.col("Metadata_Well") == "A04") & (pl.col("Metadata_Plate") == 32))

shape: (9, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Metadata_ ┆ Metadata_ ┆ Metadata_ ┆ Count_Nuc ┆ … ┆ ImageQual ┆ Intensity ┆ Ratio     ┆ Ratio    │
│ Plate     ┆ Well      ┆ Field     ┆ lei       ┆   ┆ ity_Total ┆ _Percenti ┆ P10/P90   ┆ Intensit │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ Area_Syto ┆ le_90_Syt ┆ ---       ┆ y        │
│ i64       ┆ str       ┆ i64       ┆ f64       ┆   ┆ ---       ┆ o         ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ ---       ┆           ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 32        ┆ A04       ┆ 5         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.023743  ┆ 0.624036  ┆ 0.019841 │
│ 32        ┆ A04       ┆ 9         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.02359   ┆ 0.628719  ┆ 0.019522 │
│ 32        ┆ A04       ┆ 8         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.024002  ┆ 0.622378  ┆ 0.02083  │
│ 32        ┆ A04       ┆ 3         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.024094  ┆ 0.619379  ┆ 0.021453 │
│ 32        ┆ A04       ┆ 7         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.024048  ┆ 0.629442  ┆ 0.020906 │
│ 32        ┆ A04       ┆ 6         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.024186  ┆ 0.629653  ┆ 0.020708 │
│ 32        ┆ A04       ┆ 2         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.024125  ┆ 0.623656  ┆ 0.02068  │
│ 32        ┆ A04       ┆ 4         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.023835  ┆ 0.62484   ┆ 0.020294 │
│ 32        ┆ A04       ┆ 1         ┆ 0.0       ┆ … ┆ 1166400   ┆ 0.024491  ┆ 0.625545  ┆ 0.020519 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Evaluando flagged sites

In [2]:
from pathlib import Path

In [4]:
path_parquet = Path("/mnt/czolab-storage-01/acruzcar/MAINCE_output/Cohort3/V01/QC/Collages/Cohort3_flagged_sites.parquet")
df = pl.read_parquet(path_parquet)

In [5]:
df

shape: (4_554, 36)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ Metadata_P ┆ Metadata_W ┆ Metadata_F ┆ Count_Cell ┆ … ┆ ImageQual ┆ Ratio_P10 ┆ fail ┆ failed_cr │
│ late       ┆ ell        ┆ ield       ┆ s          ┆   ┆ ity_Total ┆ /P90      ┆ ---  ┆ iteria    │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ Area_Brig ┆ ---       ┆ bool ┆ ---       │
│ str        ┆ str        ┆ i64        ┆ f64        ┆   ┆ htf…      ┆ f64       ┆      ┆ list[str] │
│            ┆            ┆            ┆            ┆   ┆ ---       ┆           ┆      ┆           │
│            ┆            ┆            ┆            ┆   ┆ i64       ┆           ┆      ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ 23         ┆ H08        ┆ 1          ┆ 63.0       ┆ … ┆ 1166400   ┆ 0.13869   ┆ true ┆ ["low_cel │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ l_count"] │
│ 23         ┆ H08        ┆ 9          ┆ 56.0       ┆ … ┆ 1166400   ┆ 0.137812  ┆ true ┆ ["low_cel │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ l_count"] │
│ 23         ┆ H08        ┆ 6          ┆ 70.0       ┆ … ┆ 1166400   ┆ 0.134094  ┆ true ┆ ["slope:B │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ rightfiel │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ d"]       │
│ 23         ┆ H08        ┆ 8          ┆ 53.0       ┆ … ┆ 1166400   ┆ 0.115301  ┆ true ┆ ["cells_n │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ uclei_rat │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ io",      │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ "low_ce…  │
│ 23         ┆ H08        ┆ 7          ┆ 53.0       ┆ … ┆ 1166400   ┆ 0.132598  ┆ true ┆ ["cells_n │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ uclei_rat │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ io",      │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ "low_ce…  │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …    ┆ …         │
│ 29         ┆ F08        ┆ 8          ┆ 112.0      ┆ … ┆ 1166400   ┆ 0.099157  ┆ true ┆ ["slope:G │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ olgi",    │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ "slope:Br │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ ightf…    │
│ 29         ┆ F08        ┆ 5          ┆ 107.0      ┆ … ┆ 1166400   ┆ 0.08621   ┆ true ┆ ["slope:H │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ oechst"]  │
│ 29         ┆ F08        ┆ 4          ┆ 105.0      ┆ … ┆ 1166400   ┆ 0.0867    ┆ true ┆ ["slope:E │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ R"]       │
│ 29         ┆ E05        ┆ 5          ┆ 122.0      ┆ … ┆ 1166400   ┆ 0.080391  ┆ true ┆ ["slope:G │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ olgi",    │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ "slope:Sy │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ to"]      │
│ 29         ┆ E05        ┆ 4          ┆ 127.0      ┆ … ┆ 1166400   ┆ 0.082332  ┆ true ┆ ["slope:G │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ olgi",    │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ "slope:Sy │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ to"]      │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

In [7]:
df.select(pl.col("fail").value_counts())

shape: (1, 1)
┌─────────────┐
│ fail        │
│ ---         │
│ struct[2]   │
╞═════════════╡
│ {true,4554} │
└─────────────┘

In [1]:
import json
path_report_html = "/mnt/czolab-storage-01/acruzcar/Data_benchmarks_output/JUMP_MoA/V01/QC/Collages/JUMP_MoA_QC_report.html"
s = open(path_report_html, encoding='utf-8').read()
i = s.index('window.__QC__ = ') + len('window.__QC__ = ')
try:
    obj, end = json.JSONDecoder().raw_decode(s, i)
    print('payload OK, claves:', list(obj))
    print('placas:', list(obj['data']))
    print('lo que sigue:', repr(s[end:end+80]))
except Exception as e:
    print('payload ROTO:', e)
    print(repr(s[i:i+200]))

payload OK, claves: ['n_rows', 'n_cols', 'data', 'countRanges', 'mfi', 'radius', 'specs', 'madScores', 'redCounts', 'robustMetrics', 'colorSpec', 'pca']
placas: ['P25', 'P26', 'P27', 'P28', 'P29', 'P30', 'P31', 'P32', 'P33', 'P34']
lo que sigue: ';\n// ───────────────────────────────────────────────────────────────────────────'

In [2]:
from collections import defaultdict
s = open(path_report_html, encoding='utf-8').read()
i = s.index('window.__QC__ = ') + len('window.__QC__ = ')
obj, _ = json.JSONDecoder().raw_decode(s, i)
mb = lambda x: len(json.dumps(x, separators=(',', ':'))) / 1e6

print(f"archivo: {len(s)/1e6:.0f} MB")
for k, v in obj.items():
    print(f"{k:12s} {mb(v):8.1f} MB")

print('--- data: suma de todas las placas ---')
agg = defaultdict(float)
for p, d in obj['data'].items():
    for k, v in d.items():
        agg[k] += mb(v)
for k, v in sorted(agg.items(), key=lambda x: -x[1]):
    print(f"{k:14s} {v:8.1f} MB")

print('pozos marcados por placa:',
      {p: len(d['flagged_b64']) for p, d in obj['data'].items()})
print('--- mfi ---')
for k, v in obj['mfi'].items():
    print(f"mfi.{k:12s} {mb(v):8.1f} MB")

archivo: 560 MB
n_rows            0.0 MB
n_cols            0.0 MB
data            490.7 MB
countRanges       0.0 MB
mfi              52.9 MB
radius            0.2 MB
specs             0.0 MB
madScores         3.0 MB
redCounts         0.0 MB
robustMetrics      0.0 MB
colorSpec         0.0 MB
pca               0.2 MB
--- data: suma de todas las placas ---
flagged_b64       424.8 MB
site_data          40.9 MB
overview_b64       12.2 MB
collage_b64         6.7 MB
wells               5.7 MB
well_flags          0.4 MB
pass_rate           0.0 MB
n_wells             0.0 MB
n_illum             0.0 MB
overview_cw         0.0 MB
overview_ch         0.0 MB
n_pass              0.0 MB
pozos marcados por placa: {'P25': 384, 'P26': 384, 'P27': 384, 'P28': 384, 'P29': 384, 'P30': 384, 'P31': 384, 'P32': 384, 'P33': 384, 'P34': 384}
--- mfi ---
mfi.data              3.5 MB
mfi.channels          0.0 MB
mfi.colors            0.0 MB
mfi.img               0.5 MB
mfi.sites             4.8 MB
mfi.imgSites         44.1 MB
mfi.cohortMedian      0.0 MB

In [3]:
flagged_b64 = dict(list(flagged_b64.items())[:20])   # SOLO PARA PROBAR

NameError: name 'flagged_b64' is not defined